import './globals.css';
import Providers from './providers';
import Header from '@/components/Header';

export const metadata = {
  title: 'aybrk.dev',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
